site_name: Welcome to Vizome
theme: mkdocs
pages:
- Home: index.md
- Modules:
  - 1. Sample attributes view: samples.md
  - 2. Variant filters and search: variants.md
  - 3. Gene sets: gene_sets.md
  - 4. Mosaic view: mosaic.md
  - 5. Individual view: individual.md
  - 6. Compare gene variants view: compare.md
  - 7. Expression stratification view: expression.md
  - 8. Chronology view: chronology.md
  - 9. Gene model view: individual.md
  - 10. Protein view: protein.md
  - 11. Inhibitor view: inhibitor.md
  - 12. HitWalker: hitwalker.md
- Tutorials: 
  - Index: tutorials.md
  - Individuals: tutorial_individual.md
- About:
  - Contributors & Contacts: contributors.md
